stages:
  get_data:
    cmd: python src/get_data.py data/train.txt data/test.txt data/val.txt
    deps:
    - src/get_data.py
    - data/test.txt
    - data/train.txt
    - data/val.txt
    outs:
    - output/raw_x_test.joblib
    - output/raw_x_train.joblib
    - output/raw_x_val.joblib
    - output/raw_y_test.joblib
    - output/raw_y_train.joblib
    - output/raw_y_val.joblib
    
  preprocess:
    cmd: python src/process_data.py
    deps:
    - src/process_data.py
    - output/raw_x_test.joblib
    - output/raw_x_train.joblib
    - output/raw_x_val.joblib
    - output/raw_y_test.joblib
    - output/raw_y_train.joblib
    - output/raw_y_val.joblib

    outs:
    - csv_files/x_test.csv
    - csv_files/x_train.csv
    - csv_files/x_val.csv
    - csv_files/y_test.csv
    - csv_files/y_train.csv
    - csv_files/y_val.csv
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - src/process_data.py
    - src/model.py
    outs:
    - models/phishing_model.h5
    metrics:
    - models/summary.json

